{% set version = "3.6.0" %}

package:
  name: colmap
  version: {{ version }}

source:
  git_url: https://github.com/colmap/colmap
  git_rev: 3.6
  

build:
  number: 1
  # https://github.com/dcnieho/FreeGLUT/issues/27
  # Maybe someday we'll build with X11 on osx:
  # https://github.com/Homebrew/homebrew-core/blob/master/Formula/freeglut.rb
  skip: true                      # [osx]

requirements:
  build:
    - cmake
    - git
    - {{ compiler('c') }}               # [linux]
    - {{ compiler('cxx') }}             # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libxfixes-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('mesa-libegl-devel') }}    # [linux]
    - {{ cdt('libxdamage') }}           # [linux]
    - {{ cdt('libxfixes') }}            # [linux]
    - {{ cdt('libxxf86vm') }}           # [linux]
    - {{ cdt('mesa-dri-drivers') }}     # [linux]
    - {{ cdt('libselinux') }}           # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
  host:
    - boost-cpp {{ boost }}
    - ceres-solver
    - cgal
    - eigen
    - freeimage
    - glew
    - qt
  run:
    - {{ pin_compatible('boost-cpp', max_pin='1.72.x') }}
    - ceres-solver
    - cgal
    - eigen
    - freeimage
    - glew
    - qt

test:
  commands:
    # Test includes.
    - test -d "${PREFIX}/include/GL"  # [linux]

      # Test libraries.
    - test -f "${PREFIX}/bin/colmap"   # [linux]

    # Test Windows includes and libraries.
    - if not exist %LIBRARY_BIN%\\colmap             exit 1   # [win]

about:
  home: http://colmap.github.io/
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Rigid SfM.

extra:
  recipe-maintainers:
    - hassony2
